from typing import Any

def GetWindowText(hwnd: int) -> str: ...
def GetClassName(hwnd: int) -> str: ...
def IsWindowVisible(hwnd: int) -> bool: ...
def GetParent(hwnd: int) -> int: ...
def EnumWindows(callback: Any, extra: Any) -> None: ...
def IsWindow(hwnd: int) -> bool: ...
def GetForegroundWindow() -> int: ...
def GetWindowRect(hwnd: int) -> tuple[int, int, int, int]: ...
def GetWindowRect(hwnd: int) -> tuple[int, int, int, int]: ...
def SetWindowPos(hwnd: int, hwndInsertAfter: int, x: int, y: int, cx: int, cy: int, flags: int) -> None: ...
def GetWindowPlacement(hwnd: int) -> Any: ...
def ShowWindow(hwnd: int, nCmdShow: int) -> None: ...
def MoveWindow(hwnd: int, x: int, y: int, width: int, height: int, repaint: bool) -> None: ...
def GetWindowLong(hwnd: int, index: int) -> int: ...
